# Generated by Django 5.0.3 on 2024-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genscene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('actor_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('assistant_id', models.CharField(max_length=200, null=True)),
                ('instructions', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=1000)),
                ('hash', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('file_id', models.CharField(max_length=200, null=True)),
                ('hash', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('thread_id', models.CharField(max_length=200)),
                ('current', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('origin_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
