# Generated by Django 5.0.3 on 2024-05-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genscene', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.TextField(),
        ),
    ]
